name       : devedeng
version    : 4.8.12
release    : 1
source     :
    - https://github.com/rastersoft/devedeng/archive/4.8.12.tar.gz : 4b01434e705bde59138caebde6c838017664a0e0a12ef11ec85161c03ea19a99
license    : GPL-3.0
component  : multimedia.video
summary    : A program to create VideoDVDs and CDs
description: |
    Devede NG is a rewrite of the Devede DVD disc authoring program. This new code has been writen from scratch, and uses Python3 and Gtk3. It is also cleaner, which will allow to add new features in the future.
rundeps    :
    - cdrtools
    - dvdauthor
    - libgtk-3
    - python-urllib3
    - python3-cairo
    - python3-gobject
    - vcdimager
build      : |
    %python3_setup
install    : |
    %python3_install

