name       : devedeng
version    : 4.11.0
release    : 3
source     :
    - https://github.com/rastersoft/devedeng/archive/4.11.0.tar.gz : b523a2026a26f10e634d72bc4aae56bb5dc70c8c34a0e2adce9e6bab132f7780
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A program to create VideoDVDs and CDs
description: |
    Devede NG is a rewrite of the Devede DVD disc authoring program. This new code has been writen from scratch, and uses Python3 and Gtk3. It is also cleaner, which will allow to add new features in the future.
rundeps    :
    - cdrtools
    - dvdauthor
    - libgtk-3
    - python-urllib3
    - python3-cairo
    - python3-gobject
    - vcdimager
build      : |
    %python3_setup
install    : |
    %python3_install
