name       : devedeng
version    : 4.12.0
release    : 4
source     :
    - https://gitlab.com/rastersoft/devedeng/-/archive/4.12.0/devedeng-4.12.0.tar.bz2 : 8a481686c3ff477a3e9c39154797b017d3a8948e044752ec5d8b6f69e845b307
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A program to create VideoDVDs and CDs
description: |
    Devede NG is a rewrite of the Devede DVD disc authoring program. This new code has been writen from scratch, and uses Python3 and Gtk3. It is also cleaner, which will allow to add new features in the future.
rundeps    :
    - cdrtools
    - dvdauthor
    - libgtk-3
    - python-urllib3
    - python3-cairo
    - python3-gobject
    - vcdimager
build      : |
    %python3_setup
install    : |
    %python3_install
