name       : devedeng
version    : 4.9.0
release    : 2
source     :
    - https://github.com/rastersoft/devedeng/archive/4.9.0.tar.gz : 380b6b60b8b155d0f7f4260d618a15fdc4922fbe77211ade2b62f2ced46fc7d8
license    : GPL-3.0-only
component  : multimedia.video
summary    : A program to create VideoDVDs and CDs
description: |
    Devede NG is a rewrite of the Devede DVD disc authoring program. This new code has been writen from scratch, and uses Python3 and Gtk3. It is also cleaner, which will allow to add new features in the future.
rundeps    :
    - cdrtools
    - dvdauthor
    - libgtk-3
    - python-urllib3
    - python3-cairo
    - python3-gobject
    - vcdimager
build      : |
    %python3_setup
install    : |
    %python3_install
