name       : devedeng
version    : 4.16.0
release    : 10
source     :
    - https://gitlab.com/rastersoft/devedeng/-/archive/4.16.0/devedeng-4.16.0.tar.bz2 : fe2715aa8f73133fc2d809d840fd662dcf9776fcedfb68169984af2e762b5164
license    : GPL-3.0-only
component  : multimedia.video
summary    : A program to create VideoDVDs and CDs
description: |
    Devede NG is a rewrite of the Devede DVD disc authoring program. This new code has been writen from scratch, and uses Python3 and Gtk3. It is also cleaner, which will allow to add new features in the future.
rundeps    :
    - cdrtools
    - dvdauthor
    - libgtk-3
    - python-urllib3
    - python3-cairo
    - python-gobject
    - vcdimager
build      : |
    %python3_setup
install    : |
    %python3_install
